version: '3.8'

services:
  web:
    build: .
    command: ./start.sh   # default command for production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/usr/src/app
      - /home/stock/Documents/UNICEF/test 100/:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - worker
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - MEDIA_FILES=/usr/src/app/media
      - CELERY_BROKER_URL=redis://redis:6379/0 

  web-dev:   # extra service for local testing (__main__.py)
    build: .
    command: python3 -m recognizeapp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/usr/src/app
      - /home/stock/Documents/UNICEF/test 100/:/usr/src/app/media
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - db
      - worker
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - MEDIA_FILES=/usr/src/app/media
      - CELERY_BROKER_URL=redis://redis:6379/0 

  worker:   # Celery worker
    build: .
    command: celery -A recognizeapp worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - MEDIA_FILES=/usr/src/app/media
      - CELERY_BROKER_URL=redis://redis:6379/0 

  flower:   # Celery monitoring UI
    build: .
    command: celery -A recognizeapp flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0 

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dbname

  redis:
    restart: always
    image: redis
    expose:
      - "6379"

volumes:
  postgres_data:
